# Generated by Django 4.1.6 on 2023-02-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("borrowings_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")],
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Payment", "Payment"), ("Fine", "Fine")],
                        max_length=10,
                    ),
                ),
                ("session_url", models.URLField(max_length=255)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings_service.borrowings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payments",
                "verbose_name_plural": "Payments",
                "ordering": ("-money_to_pay",),
            },
        ),
    ]
