version: "3"

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

#  flower:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    command: "celery -A library_service flower --address=0.0.0.0"
#    depends_on:
#      - -celery
#    env_file:
#      - .env
