# Generated by Django 4.1.6 on 2023-02-08 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="daily_free",
            new_name="daily_fee",
        ),
    ]
