# Generated by Django 4.1.6 on 2023-02-16 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField()),
                (
                    "expected_return_date",
                    models.DateField(default=datetime.date(2023, 2, 17)),
                ),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to="book_service.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Borrowings",
                "verbose_name_plural": "Borrowings",
                "ordering": ["expected_return_date"],
            },
        ),
    ]
