# Generated by Django 4.1.6 on 2023-02-04 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="actual_return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrowings",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 5, 19, 27, 18, 892499, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
