# Generated by Django 4.1.6 on 2023-02-05 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0002_alter_borrowings_actual_return_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowings",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowings",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="borrowings",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 6, 12, 6, 16, 29864, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
