# Generated by Django 4.1.6 on 2023-02-08 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0003_rename_book_id_borrowings_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="borrow_date",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="borrowings",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 9, 16, 31, 18, 120511, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
