# Generated by Django 4.1.6 on 2023-02-08 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0005_alter_borrowings_expected_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 9, 18, 47, 5, 391014, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
