# Generated by Django 4.1.6 on 2023-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0006_alter_borrowings_expected_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="expected_return_date",
            field=models.DateTimeField(),
        ),
    ]
