# Generated by Django 4.1.6 on 2023-02-15 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0007_alter_borrowings_expected_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="borrow_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="borrowings",
            name="expected_return_date",
            field=models.DateTimeField(default=datetime.date(2023, 2, 16)),
        ),
    ]
