# Generated by Django 4.1.6 on 2023-02-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0008_alter_borrowings_borrow_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
